### ISSUE TITLE
狗哥 出错了ERROR ore::send_and_confirm] Err: Error { request: Some(GetTransaction), 

### ISSUE THREAD

**Issue by piqihaha** [GoudanWoo/ore-cli-noerr#1]
![image](https://github.com/GoudanWoo/ore-cli-noerr/assets/25221169/e91add49-bda8-4dc3-b010-60333e2b47a8)
这什么情况呢 狗哥

**Comment by Pengu1ncc** [comment]
正常情况

**Comment by WankkoRee** [comment]
正常情况，我这一版特色，就是一直在等待交易出块，如果长时间不出块，需要提高fee。

**Comment by GoudanWoo** [comment]
正常情况，我这一版特色，就是一直在等待交易出块，如果长时间不出块，需要提高fee。

**Comment by piqihaha** [comment]
好的谢谢 几位哥，希望你们别骗我，因为那么大的ERROR看了吓人

**Comment by piqihaha** [comment]
fee写多少合适呢 哥

**Comment by GoudanWoo** [comment]
我现在测试是`20000000`能稳定出，但是还取决于RPC打包能力，有些RPC打包能力弱的，你给再高都不出。

**Comment by piqihaha** [comment]
> 我现在测试是`20000000`能稳定出，但是还取决于RPC打包能力，有些RPC打包能力弱的，你给再高都不出。

卧槽，完犊子，我都设置100呢。我改下试试
20000000 是多少SOL呢 ？

**Comment by GoudanWoo** [comment]
`0.000069` SOL

**Comment by piqihaha** [comment]
> `0.000069` SOL

好的哥 马上改

**Comment by piqihaha** [comment]
哥，大恩不言谢，等发财了，再来报答你
还有个问题，哥，一个号开一个窗口就可以了吗 ？还是一个号多开？

**Comment by GoudanWoo** [comment]
别单钱包多开，会烧gas的。

**Comment by piqihaha** [comment]
> 别单钱包多开，会烧gas的。

明白了 狗哥，谢谢狗哥，爱你狗哥

**Comment by zhaoguijie** [comment]
哥，命令行怎么启动啊

**Comment by qianse** [comment]
大佬给个联系方式，我想加你，有偿解答，Q211900026 加我详聊
